version: 2.1

jobs:
  create_infrastructure:
    docker:
      # docker image that ansible needs to execute
      - image: python:3.7-alpine3.11s
    steps:
      - checkout
      - add_ssh_keys:
          fingerprints: ["93:37:86:ea:0e:34:8a:ca:5a:25:18:42:3d:86:45:ac"]
      - run:
          name: install dependencies
          command: |
            apk add --update ansible 
      - run:
          name: Configure Server
          command: |
            ansible-playbook -i inventory.txt playbook.yml

workflows:
  my_workflow:
    jobs:
      - create_infrastructure
