version: 2.1

docker-def: &docker-def
    docker:
      - image: amazon/aws-cli

jobs:
  create_infrastructure:
    <<: *docker-def
    steps:
      checkout
      - run:
        name: build infra 
        command: |
          aws cloudformation deploy --stack-name ansible-ec2  --template-file file://template.yml --capabilities "CAPABILITY_IAM" "CAPABILITY_NAMED_IAM" --region=us-west-2


workflows:
  wf-create-infra:
    jobs: 
      - create_infrastructure
