version: 2.1

jobs:
  create_infrastructure:
    docker:
      # docker image that ansible needs to execute
      - image: python:3.7-alpine3.11
    steps:
      - checkout
      - add_ssh_keys:
          fingerprints: ["93:37:86:ea:0e:34:8a:ca:5a:25:18:42:3d:86:45:ac"]
      - run:
          name: install dependencies
          command: |
            apk add --update ansible 
      # - run:
      #     name: Disable key checking
      #     command: |
      #       export ANSIBLE_HOST_KEY_CHECKING=False
      - run:
          name: Configure Server
          command: |
            ANSIBLE_HOST_KEY_CHECKING=False ansible-playbook -i inventory.txt playbook.yml
  smoke_test:
    docker:
      - image: alpine:latest
    steps:
      - run: apk add --update curl
      - run:
          name: smoke test.
          command: |
            URL="34.222.14.189" 
            if curl -s --head ${URL}
            then
              return 0
            else
              return 1
            fi

workflows:
  my_workflow:
    jobs:
      - create_infrastructure
      - smoke_test:
        requires:
          - configure_infrastructure
